# @copyright Copyright (c) contributors to Project Ocre,
# which has been established as Project Ocre a Series of LF Projects, LLC
#
# SPDX-License-Identifier: Apache-2.0

name: Formatting checks

on:
  workflow_call:
    inputs:
      devcontainer-tag:
        description: The container tag to be used
        default: latest
        required: false
        type: string

jobs:
  format-checks:
    name: Formatting checks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/devcontainer-linux:${{ inputs.devcontainer-tag }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run C Format Checks
        run: sh scripts/check_c_formatting.sh
