# @copyright Copyright (c) contributors to Project Ocre,
# which has been established as Project Ocre a Series of LF Projects, LLC
#
# SPDX-License-Identifier: Apache-2.0

name: Linux

on:
  workflow_call:
    inputs:
      devcontainer-tag:
        description: The container tag to be used
        default: latest
        required: false
        type: string

jobs:
  build-linux:
    name: Linux build
    runs-on: self-hosted
    container:
      image: ghcr.io/${{ github.repository }}/devcontainer-linux:${{ inputs.devcontainer-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure (system tests)
        run: mkdir build && cd build && cmake ../tests/system/posix

      - name: Build (system tests)
        working-directory: build
        run: make

      - name: Run (system tests)
        working-directory: build
        run: make run-systests

      - name: Delete build directory
        run: rm -rf build

      - name: Configure (leak checks)
        run: mkdir build && cd build && cmake ../tests/leaks

      - name: Build and run (leak checks)
        working-directory: build
        run: make

      - name: Delete build directory
        run: rm -rf build

      - name: Configure (source coverage)
        run: mkdir build && cd build && cmake ../tests/coverage

      - name: Build and run (source coverage)
        working-directory: build
        run: make

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: ocre-coverage
          include-hidden-files: true
          path: build/report

      - name: Delete build directory
        run: rm -rf build

      - name: Configure
        run: mkdir build && cd build && cmake ..

      - name: Build
        working-directory: build
        run: make

      - name: Run mini
        working-directory: build
        run: |
          EXPECTED_LOG="powered by Ocre"
          echo "Running application..."
          stdbuf -oL -eL timeout 20s ./src/samples/mini/posix/ocre_mini | tee linux_run.log
          echo "===== Checking for expected log ====="
          if grep -q "$EXPECTED_LOG" linux_run.log; then
            echo "[OK] Found expected log: $EXPECTED_LOG"
          else
            echo "[ERROR] Expected log not found: $EXPECTED_LOG"
            exit 1
          fi

      - name: Run demo
        working-directory: build
        run: |
          EXPECTED_LOG="Demo completed successfully"
          echo "Running application..."
          stdbuf -oL -eL timeout 40s ./src/samples/demo/posix/ocre_demo | tee linux_run.log
          echo "===== Checking for expected log ====="
          if grep -q "$EXPECTED_LOG" linux_run.log; then
            echo "[OK] Found expected log: $EXPECTED_LOG"
          else
            echo "[ERROR] Expected log not found: $EXPECTED_LOG"
            exit 1
          fi
