name: Linux

on:
  workflow_call:
    inputs:
      devcontainer-tag:
        description: The container tag to be used
        default: latest
        required: false
        type: string
      ref:
        type: string
        required: true

jobs:
  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/devcontainer-linux:${{ inputs.devcontainer-tag }}
      options: --user 1001:127
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: mkdir build && cd build && cmake ..

      - name: Build
        working-directory: build
        run: make

      - name: Run mini
        working-directory: build
        run: |
          EXPECTED_LOG="powered by Ocre"
          echo "Running application..."
          stdbuf -oL -eL timeout 20s ./src/samples/mini/posix/ocre_mini | tee linux_run.log
          echo "===== Checking for expected log ====="
          if grep -q "$EXPECTED_LOG" linux_run.log; then
            echo "[OK] Found expected log: $EXPECTED_LOG"
          else
            echo "[ERROR] Expected log not found: $EXPECTED_LOG"
            exit 1
          fi

      - name: Run demo
        working-directory: build
        run: |
          EXPECTED_LOG="Demo completed successfully"
          echo "Running application..."
          stdbuf -oL -eL timeout 40s ./src/samples/demo/posix/ocre_demo | tee linux_run.log
          echo "===== Checking for expected log ====="
          if grep -q "$EXPECTED_LOG" linux_run.log; then
            echo "[OK] Found expected log: $EXPECTED_LOG"
          else
            echo "[ERROR] Expected log not found: $EXPECTED_LOG"
            exit 1
          fi
